AppBundle\Entity\iwh\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\iwh\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        password:
            type: string
            length: 255
        userName:
            type: string
            length: 255
            unique: true
            column: user_name
    lifecycleCallbacks: {  }
